name: Trigger auto deployment for laptopserver-app-20260330234553

# When this action will be executed
on:
  push:
    branches: 
      [ main ]
    paths:
    - 'laptop_server/**'
    - '.github/workflows/laptopserver-app-20260330234553-AutoDeployTrigger-8d9a0b5e-e751-4533-a301-41c33460f290.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LAPTOPSERVERAPP20260330234553_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LAPTOPSERVERAPP20260330234553_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LAPTOPSERVERAPP20260330234553_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/laptop_server
          dockerfilePath: dockerfile
          registryUrl: laptopserver20260330234729.azurecr.io
          registryUsername: ${{ secrets.LAPTOPSERVERAPP20260330234553_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LAPTOPSERVERAPP20260330234553_REGISTRY_PASSWORD }}
          containerAppName: laptopserver-app-20260330234553
          resourceGroup: Potuzhni-laptops
          imageToBuild: laptopserver20260330234729.azurecr.io/laptopserver-app-20260330234553:${{ github.sha }}